### ISSUE TITLE
Application doesn't work with Oculus Rift

### ISSUE THREAD

**Issue by hir1m** [derole1/MaiMai-VR#2] opened 2020-04-07 04:37 UTC
I tried to use it on a rift. The program opens fine, however, the game won't be projected onto the rift's display. It does open a window that looks like this:

![Capture1](https://user-images.githubusercontent.com/23530587/78630372-6b3a8180-784e-11ea-8749-a8df41da0838.PNG)

The vr controls also do not work properly. I do have a second display that is able to see where the vr headset is currently located in the application. When I do move the headset physically, the headset in the camera view does not move at all.

Something worth noting is that the rift indeed senses the game activity; the rift simply becomes unresponsive while the game is active - with a dark screen and unable to open system menu with the touch controls. Everything goes back to normal in the rift after I close the game.

I also tried opening the game while SteamVR is active, the same thing happens.

**Comment by J0nny0** [comment] 2020-04-12 15:07
Derole knows about this since the version 0.1 since I tried it back then with the normal rift (nowadays the Rift s) and told him about it... as of now he dont have a fix for it... BUT if u know how to work with Unity u might can fix the errors in Unity and compile it for the Rift users.

**Comment by JoeKoh27** [comment] 2020-04-14 21:03
Tried it on my Rift S and pretty much got the same issue

**Comment by derole1** [comment] 2020-04-15 18:38
Yeah unfortunately I do not have a rift to debug this with so its hard for me to debug. I will leave the issue open incase I stumble upon a fix.

**Comment by JoeKoh27** [comment] 2020-04-22 11:02
So I decided to download the Source file and see if I can mess around with it, I realized that changing the VRcamera to Oculus' OVRcameraRig will allow the tracking to work with the Rift S. But I didnt get to playtest it as I'm not familiar with Unity. The controllers also only track when I have the headset off instead of when I'm wearing my headset.

**Comment by JoeKoh27** [comment] 2020-04-22 11:58
So I downloaded the Source and played around with it a little, I realized to get Oculus Head Tracking to work, you need to use OVRcameraRig from the Oculus Integration Asset instead. Unfortunately I'm not experienced in Unity nor coding so I cant get any further than getting the Head Tracking to work. Meaning I couldn't find a way to make the Oculus Touch controllers to work.

Maybe you could get the Oculus Integration asset and see for yourself if there's anything that you can possibly use.

**Comment by aurelienfr** [comment] 2020-07-23 19:20
HI, i found a fix to this issue, you have to disable oculus support in the xr setting, doing that make the game  always launch with steamvr, the only issue remaning after that is the rumble, that sometime bug and don't turn off, you can turn it off by pushing the trigger, apart from that everything is playable with my rift s.

**Comment by JoeKoh27** [comment] 2020-08-04 03:24
> the only issue remaning after that is the rumble

You can disable rumble by setting the Haptic to "None" in both LeftHand and RightHand entries

**Comment by mon4rkh** [comment] 2020-08-11 07:36
> you have to disable oculus support in the xr setting

sorry dumb question but how do you do that

**Comment by JoeKoh27** [comment] 2020-08-11 07:40
> > sorry dumb question but how do you do that

Go to Bulid Settings, navigate to the XR Settings, highlight the Oculus section and press the - icon at the bottom right

**Comment by derole1** [comment] 2020-08-12 08:45
I have updated with a version with oculus support off, please tell me if this fixes the issue

**Comment by CuriousCod** [comment] 2020-08-19 12:25
I can confirm that the application works with Rift CV1 now.

**Comment by hir1m** [comment] 2020-08-24 07:48
works on og rift

**Comment by derole1** [comment] 2020-08-24 10:07
Awesome to hear! Will close the issue.

**Closed as completed by derole1** 2020-08-24 10:07 UTC
